### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by jmank88** [gochain/netstats#38]
The layout is already somewhat reactive (#13,#32), but The current `min-width` is `1000px` (and possibly wider for the table depending on data). We should reduce this as much as possible. Reducing this further requires 2 major changes:
- [ ] Making the map scalable
- [x] Table rows: convert to cards, or drop some columns (#48)

Smaller requirements:
- [ ] Improve chart scaling (#49)
- [x] Various font/icon scaling (#48)
